mapbox/mapbox-gl-draw

src/draw.js
src/store.js

re: https://github.com/mapbox/gl-draw/issues/5 and part of https://github.com/mapbox/gl-draw/issues/26
Next action is to add a button that also does this

Add feature deletion

---

index.js
src/draw.js
src/edit_store.js
src/handlers/line.js
src/handlers/point.js
src/handlers/polygon.js
src/handlers/square.js

Bonus: also simplifies the logic for dragging regular vertices and makes it much more efficient! Hellz yeah bruh

add vertex

---

package.json

Closes #120
@scothis for the review

move mapbox-gl to a peer dependency

---

README.md

example folder names changed looks like

incorrect example urls in readme

---

API.md
CHANGELOG.md
debug/index.html

Fixes the docs side of #162 and updates the changelog to show the event name changes.

Fix event docs

---

API.md
debug/index.html
src/api.js
src/geometries/geometry.js

Set drawId on .add via the feature id property

---

debug/index.html
src/theme/draw-selected.js
src/theme/draw.js

Fix default styles to strictly follow the style spec.
Users with custom styles should review the new styles
to see what values need to be removed and replaced.
https://www.mapbox.com/mapbox-gl-style-spec/ is a good resource
for working out this sorts of bugs.

Upgrade mapbox-gl-js to 0.13.1

---

package.json
src/api.js
src/draw.js
src/draw_events.js
src/feature_types/feature.js
src/store.js
test/controls.test.js
test/events.test.js
test/line.test.js
test/polygon.test.js
test/square.test.js

We had a bunch of failed things in our last build that would have been caught by our tests if they were being run. This PR tries to start fixing those bugs and get out tests running.

Test fall out

---

src/draw.js
src/draw_events.js
src/store.js

@rbonillajr or @averas can one of you confirm that this fixes the map zoom trash can error from #166?

Don't show trashcan when nothing is selected - fixes #166

---

src/draw_events.js
src/feature_types/feature.js
src/feature_types/line.js
src/feature_types/polygon.js

Fix end of drawing

---

debug/index.html
package.json

Has debug use node_modules/mapbox-gl

---

src/api.js
src/draw.js
src/draw_events.js
src/feature_types/feature.js
src/feature_types/line.js
src/feature_types/polygon.js
src/lib/create_midpoints.js
src/store.js
src/theme/draw-selected.js

This PR implements clicking on a vertex to delete it to close #210. It implements using escape to revert changes when editing a feature.

Delete nodes and revert change

---

API.md
debug/index.html
src/api.js
src/draw.js
src/draw_events.js
test/api.test.js
test/events.test.js
test/line.test.js
test/point.test.js
test/polygon.test.js
test/square.test.js

add startDrawing to public API [WIP]

---

src/draw.js
test/draw.test.js

Added a similar check for calling `_showDeleteButton` as well

Resolve 223 Show/Hide Delete Button gets additional conditionals

---

debug/index.html
src/draw.js
src/draw_events.js

re https://github.com/mapbox/mapbox-gl-draw/issues/169 and https://github.com/mapbox/mapbox-gl-draw/issues/236

remove event listeners on remove

---

src/draw.js

Solves #215.
Brings down initialization of draw from ~700ms to ~100ms and removal from ~700ms to ~90ms, which makes a great deal of difference in applications where you enable/disable draw often.
cc @mcwhittemore @kelvinabrokwa

Wrapped layer/source add/removes in batch calls

---

src/api.js

fix bug where ui doesn't update on update

---

src/lib/find_target_at.js
src/modes/draw_line_string.js

@mayagao this should make selecting lines better and should solve the bug you were having with double click to end drawing a line.

Select lines easier, double click to end drawing a line.

---

debug/index.html
index.js
package.json
src/ui.js

I kept getting a blank object when I tried using `require('mapbox-gl-draw')` with Browserify. I changed the way the module exports itself and it works now.
I also added code to support multiple ui positions similar to `mapboxgl.Navigation`

Exports fix + position option implementation

---

src/modes/draw_line_string.js
src/modes/draw_point.js
src/render.js

Rebase #283 and fix draw.changed on invalid features

---

package.json
src/api.js
test/api.test.js
test/utils.js

Closes #287 
@averas for the review

update feature properties on Draw.add even if there is no change in coords

---

API.md
package.json
src/api.js
src/events.js
src/lib/features_at.js
src/lib/find_target_at.js
src/lib/get_features_and_set_cursor.js
src/lib/is_click.js

Closes #300
Add this to the map in debug mode for a predraw fixture set
@samanpwbb for review
```
Draw.add(JSON.parse('{"type":"FeatureCollection","features":[{"id":"7e03ccfef2ede44f44f1c504f7d49645","type":"Feature","properties":{},"geometry":{"coordinates":[[[18.632812500000085,-37.02009820136845],[49.92187500000031,-30.90222470517181],[49.92187500000031,4.039617826768136],[-8.4375,5.790896812871736],[18.632812500000085,-37.02009820136845]]],"type":"Polygon"}},{"id":"e6fb3c1607d038638f5af20f1db4bb83","type":"Feature","properties":{},"geometry":{"coordinates":[[[7.031250000000085,-2.635788574166824],[20.742187500000085,-28.767659105691685],[41.83593750000023,-24.367113562651653],[43.5937500000002,-1.230374177432921],[7.031250000000085,-2.635788574166824]]],"type":"Polygon"}},{"id":"9fffbe …
```

area bassed selection

---

debug/index.html
src/lib/theme.js

clean up theme: better layer order, naming convention, styles

---

package.json
src/lib/features_at.js

wait until map is loaded to run queryRenderedFeatures, closes #320

---

dist/mapbox-gl-draw.css
src/lib/get_features_and_set_cursor.js
src/modes/draw_point.js

follow-up to https://github.com/mapbox/mapbox-gl-draw/pull/337
@mcwhittemore for review, I'll wait for you before merging this time :P

simplify css and mouse classes again

---

API.md
dist/mapbox-gl-draw.css
package.json
src/api.js
src/events.js
src/lib/common_selectors.js
src/lib/features_at.js
src/lib/get_features_and_set_cursor.js
src/lib/mode_handler.js
src/modes/simple_select.js
src/options.js
src/setup.js
src/ui.js
test/options.test.js

add box select option, closes #339

---

src/api.js

@mcwhittemore for review. no tests, so i won't close https://github.com/mapbox/mapbox-gl-draw/issues/346 yet, but I do want to get this merged.

pass new geometry to existing feature

---

src/api.js
src/feature_types/feature.js
src/feature_types/polygon.js

@samanpwbb can you review this?

render update to coords

---

src/events.js
src/ui.js

disable keybinding if corresponding control is disabled, closes #265

---

src/feature_types/polygon.js
src/modes/draw_line_string.js
src/modes/draw_polygon.js
src/modes/simple_select.js

prevent adding extra nodes to polygons, fixes #345

---

API.md
src/events.js

Relates to https://github.com/mapbox/mapbox-gl-draw/issues/314. What I'm doing here is just storing the most recent set of features after a draw.changed event, and broadcasting that most recent set of features on a mouseUp.  So this relays a message on every click while drawing a new feature, and for updating vertices on existing features.
I still need to write tests and make the existing broken ones pass.
cc/ @mcwhittemore

Modified event

---

package.json
src/lib/mode_handler.js
src/lib/simple_set.js
src/modes/direct_select.js
src/modes/draw_line_string.js
src/modes/draw_point.js
src/modes/draw_polygon.js
src/modes/simple_select.js
src/render.js
src/store.js
test/simple_set.test.js
test/store.test.js
test/utils.js

Ref #357.
This involved some refactoring to keep the selection in the store, accessible outside of simple_select. I performed some other other refactoring to clarify the API of the store and improve testability.
I tried a messing around on the debug map and everything seemed to me to work fine. Please check that I did not miss bugs or did not check everything.
cc/ @samanpwbb @mcwhittemore

Deselect deleted features; closes #357

---

package.json
src/events.js
test/events.test.js

@davidtheclark for the review
Closes #364
Closes #363

Emit new points in draw.modified and don't emit deleted features

---

src/render.js
test/utils/after_next_render.js
test/utils/make_mouse_event.js

@davidtheclark for the review
I tried to do get the afterNextRender to work right, but the spy is in some weird state and throwing errors. 32ms timeout will do for this PR.

adding in a few simple test utils

---

package.json
src/constants.js
src/lib/common_selectors.js
src/lib/is_event_at_coordinates.js
src/modes/draw_line_string.js
src/modes/draw_point.js
src/modes/draw_polygon.js
src/ui.js
test/common_selectors.test.js
test/draw_line_string.test.js
test/is_event_at_coordinates.test.js
test/test_utils.js
test/ui.test.js

draw_line_string mode tests

---

API.md

Fix select event docs; closes #391

---

src/constants.js
src/modes/draw_point.js
test/draw_line_string.test.js
test/draw_point.test.js

Add draw_point tests

---

API.md

remove mention of hover from API reference, closes #318

---

API.md
package.json
src/events.js
src/lib/common_selectors.js
src/modes/simple_select.js
src/render.js
test/api.test.js
test/events.test.js
test/simple_select.test.js
test/test_utils.js
test/utils/after_next_render.js

I was able to get this up to 60% today. Most of the time was spent [mocking query rendered features](https://github.com/mapbox/mapbox-gl-js-mock/pull/5). I think I'll be at ~100 tomorrow.
**before**
**after**
Closes #383

Simple select

---

API.md
package.json
src/api.js
src/render.js
test/api.test.js
test/interaction_events.test.js
test/simple_select.test.js

Allows applications to hard reset Draw's internals without fully blowing away what is rendered on the map

add a set function to the api

---

API.md
src/api.js
test/api.test.js

Get feature ids at point

---

src/modes/direct_select.js
test/direct_select.test.js

don't drag vertex when moving map. Closes #400

---

API.md
src/lib/mode_handler.js

remove mode_handler.fire and simple doc formatting fix

---

src/api.js
test/api.test.js
test/utils/get_geojson.js

fix Draw.add validation and add tests

---

src/feature_types/polygon.js
src/modes/draw_line_string.js
src/modes/draw_polygon.js
src/modes/simple_select.js
test/draw_line_string.test.js
test/draw_point.test.js
test/draw_polygon.test.js
test/interaction_events.test.js
test/utils/create_mock_draw_mode_context.js
test/utils/create_mock_lifecycle_context.js
test/utils/key_events.js

Closes #399
@davidtheclark for the review

Consistify exiting draw modes

---

test/mode_handler.test.js
test/utils/create_mock_mode.js
test/utils/create_mock_mode_handler_context.js

Mode handler tests; closes #370

---

server.js

We talked about this the other day ... I just want to be able to run Draw and Studio servers at the same time easily. Open to any port number if you don't like that one.

Change server port for Studio compat

---

package.json
src/modes/simple_select.js
test/simple_select.test.js

Ref #440.
This was one of those cases where to debug the problem I just had to clarify all the logic, so I understood it better and knew there weren't false moves.
So I refactored simple_select and I think it's more clear and more precise now. I believe clarifying process fixed our shift-click problems. 
The UI works as before, from what I can tell, and tests are passing (I removed two that seemed unnecessary, because UI confirmed that double-click zoom was behaving normally).

Shift clicking

---

.eslintrc
package.json
src/lib/sort_features.js
test/store.test.js
test/utils/get_geojson.js

I upgraded dependencies, made ESLint check test, and fixed the few linting errors it found.
I replaced `turf-area` with `geojson-area` because it looks like `geojson-area` is all we need. Please correct me if I'm wrong!

Upgrade dependencies, lint tests

---

src/lib/common_selectors.js
src/lib/mode_handler.js
src/modes/direct_select.js
src/modes/draw_line_string.js
src/modes/draw_polygon.js
src/modes/simple_select.js
test/common_selectors.test.js
test/draw_line_string.test.js
test/draw_polygon.test.js
test/interaction_events.test.js
test/line_string.test.js
test/point.test.js
test/polygon.test.js
test/utils/draw_geometry.js

Closes #448
I still need to fix and write some tests, but @samanpwbb what do you think of this functionality.

add marker to make click to end polygon clear

---

src/modes/direct_select.js

Ref #461.
This is still WIP because I haven't written/modified tests. But @mcwhittemore if you want to review the UI interactions, feel free.

Fix out-of-bounds dragging in direct_select; closes #461

---

package.json

closes https://github.com/mapbox/mapbox-gl-draw/issues/477

bump mapbox gl to 0.22

---

src/ui.js

* Avoiding argument-less calls to classList.remove and add

Fix IE11 crash

---

src/api.js
test/api.test.js

A less flawed continuation of #486.
Also fixes the test so that it actually catches what it should catch.

Further geojsonhint fixing

---

src/lib/create_supplementary_points.js
test/create_supplementary_points.test.js

Rebase of #485

---

API.md
src/api.js
src/events.js
src/lib/mode_handler.js
src/lib/move_features.js
src/lib/truncate_point.js
test/api.test.js
test/move_features.test.js
test/utils/create_map.js

Closes #498 
Closes #499
Closes #423

[WIP] Make sure Draw plays well with others

---

README.md

add release instructions to readme

---

src/modes/direct_select.js
src/modes/simple_select.js

Add actionable events to trash methods for simple and direct select

---

src/lib/mode_handler.js
src/lib/move_features.js
src/lib/truncate_point.js
test/move_features.test.js

Closes #534
Fixes #527
@tmcw, @ChrisBellew or @apkoponen for the review

remove truncation from draw

---

src/lib/common_selectors.js

make common_selectors declarations the same

---

API.md

remove refs to  in the api docs as this was dropped a long time ago

---

dist/mapbox-gl-draw.css
package.json
src/modes/direct_select.js
test/direct_select.test.js

This adds drag to direct_select and replaces #452.
To merge this I need to work out how to get cursors to work a bit better for direct_select mode.

Add drag to direct select

---

src/events.js
test/direct_select.test.js
test/interaction_events.test.js
test/simple_select.test.js

add better firefox drag detection

---

src/setup.js

better detection of ready to load control state

---

README.md

Small correction in `Readme`
cc @mcwhittemore

v0.14.0 -> v0.16.0

---

.travis.yml
circle.yml

Let's see if this gets CI working for all PRs.

Switch to Travis

---

package.json
src/api.js
src/lib/sort_features.js

Use mapbox-namespaced modules

---

LICENSE

Change LICENSE to ISC

---

EXAMPLES.md

your styling example does not show points because both rules filter for active = true.
imho the second one should be false.

fixed typo in example

---

API.md

@mcwhittemore I tried to 
- Clarify some things
- Fix incorrect examples
- Use Flow-style annotations instead of the idiosyncratic annotations
I do not know what the last two tables are about so did not touch them. What *are* they for? We should clarify them.

Documentation improvements

---

README.md

Closes #623
@davecranwell for the review

point users to package.json for gl-js compatbility

---

package.json

version bump for last merge to update GLJS version peer dependencies.

version 0.17.2

---

package.json

Updates GLJS and peer dependencies for GLJS again to be compatible with upcoming Studio release.

Update GLJS and peer dependencies related to GLJS

---

package.json

Version bump to 0.17.3 to update GLJS and GLJS peer dependencies.

Version bump 0.17.3

---

test/direct_select.test.js

This is a failing regression test demonstrating #632.

Test shows inaccurate selected coordinates after drag

---

API.md

add draw event example to API.md

---

src/modes/draw_line_string.js
src/modes/draw_polygon.js

dont use fake events to display coordinates

---

docs/API.md

Fix API Doc example for getFeatureIdsAt

---

src/modes/mode_interface_accessors.js
src/modes/simple_select.js
test/simple_select.test.js

Fixes #680. 
The tests are still passing, but I am not sure about unwanted side-effects. Any feedback is appreciated :)

Remove unnecessary setSelected call

---

package.json
src/lib/constrain_feature_movement.js
src/lib/mouse_event_point.js
test/mouse_event_point.test.js
yarn.lock

I don't believe these have any impact on the code that gets installed/run, but appeases warnings that clutter my build logs.

Fix some warnings

---

CHANGELOG.md

Just got these messages from the latest commits.

Update changelog v1.0.3

---

README.md

Fix import paths in Readme

---

docs/MODES.md

This PR adds to MODES.md a reference to the Cut/Split Line mode I wrote.

Adds cut-line custom mode in MODES.md

---

CHANGELOG.md
package.json

just to run the tests since I accidentally let mapbox-gl through in an earlier PR

Changelog fix gl

---

docs/MODES.md

Adding a little mode I made for rotation of features.

Add Rotate Mode to mode docs

---

docs/API.md

Fix spelling

---

src/setup.js
src/ui.js

Fixes #781.
@hyperknot for the review.

clear draw classes on remove

---

package.json

fix https://github.com/mapbox/mapbox-gl-draw/issues/889

update peer dependency

---

src/modes/simple_select.js

Change `dragMoveing` to `dragMoving`

Fix typo on property name

---

package.json

Address concern from testing: https://github.com/mapbox/mapbox-gl-draw/issues/895#issuecomment-571699021

Move eslint-plugin-import to devDependencies

---

CHANGELOG.md
src/lib/create_midpoint.js
src/lib/create_supplementary_points.js

Fixes #1027 
https://user-images.githubusercontent.com/7061573/109198906-a211d280-7753-11eb-8ecb-359b7cde397c.mov
https://user-images.githubusercontent.com/7061573/109198917-a342ff80-7753-11eb-999f-1f7e6e072049.mov

Fix midpoint calculation when terrain is enabled

---

docs/MODES.md

A mapbox gl draw mode to draw and edit bezier curves.

Add Bezier Curve mode

---

CHANGELOG.md
README.md
bench/index.html
bench/index.js
debug/index.html
package.json

The patch release includes the revert of passive event listeners in https://github.com/mapbox/mapbox-gl-draw/pull/1158

Release v1.4.1

---

docs/MODES.md

This is a custom mode for @mapbox/mapbox-gl-draw that allows user to paint freestyle on the map.

Added a custom paint mode for @mapbox/mapbox-gl-draw

---

src/modes/direct_select.js
test/direct_select.test.js

Fix disable dragPan after second click on feature
