- index.html
- src/theme/edit.js
- src/theme/style.js
- Uses `circle.sdf` for rendering points until circle types land in v8
- Switch to the streets style (which contains circles in the sprite)
- Styles midpoints in edit mode differently
> Update feature styling

- package.json
- src/draw.js
- src/edit_store.js
- src/geometries/geometry.js
- src/geometries/line.js
- src/geometries/point.js
- src/geometries/polygon.js
- src/geometries/square.js
- src/store.js
In trying to implement mass edits it has come to my attention that there are several things that can be done much better namely that stores should hold an array of `Geometry` types, not just geojson objects. This will simplify the edit code greatly. `Geometry` instances will have a `this.drawId` member constant and a `this.feature` member variable (in addition to the current methods). This way, don't have to re-instantiate `Geometry` types every time we edit.
In general, we need a greater separation of concerns across the board (a more flow-based approach).
Also
- limits the scope of group edits to just deleting features...for now ;)
- severely reduces the number of `toJS` and `fromJS` calls across the board for a performance boost
re: #4 #69
> featuresIn and mass edits also major refactor

- debug/index.html
- src/draw.js
- src/edit_store.js
- src/geometries/geometry.js
- src/geometries/line.js
- src/geometries/point.js
- src/geometries/polygon.js
- src/geometries/square.js
- src/store.js
- src/theme/drawing.js
- test/api.test.js
- test/draw.test.js
- test/edit_store.test.js
- test/store.test.js
This PR does a lot of different things, but mostly, it simplifies and cleans up [draw.js][draw], [store.js][store], and [edit_store.js][edit] a great deal by using much more sensible data structures to keep tabs of the state of the geometries. This results in A LOT less code (over 150 lines less with greatly reduced bugginess)!
It also removes history, undo, and redo for the sake for simplicity for the time being.
re: #77, #21 
[draw]: https://github.com/mapbox/gl-draw/blob/master/src/draw.js
[store]: https://github.com/mapbox/gl-draw/blob/master/src/store.js
[edit]: https://github.com/mapbox/gl-draw/blob/master/src/edit_store.js
> Drawing and editting refactor

- package.json
- src/store.js
This decreases the size of bundled versions of mapbox-gl-draw by removing turf-intersect and opting for the maps default featureIn selector.
@kelvinabrokwa or @tmcw for the review
> use featuresIn to select features for editing

- API.md
- src/draw.js
- src/edit_store.js
- src/geometries/geometry.js
- src/geometries/line.js
- src/geometries/point.js
- src/geometries/polygon.js
- src/geometries/square.js
- src/internal_events.js
- src/store.js
Currently gl-draw uses the public mapbox-gl-js event emitter for its own internal state management. This has the nice benefit of giving end users a way to connect into the gl-draw life cycle, but it also makes it hard to create good internal updates as external and internal api contacts are tightly bound. This PR separates these concerns and starts to set standards around external event naming and payload content. 
**This is a breaking change.** As we are still in 0.*.* range, this will not mean a major bump, but I want to make sure anyone who is watching  this today is aware of the direction @kelvinabrokwa and I are looking to go. I also didn't recreate all of `0.0.2`s external events. If there are no major complaints, my goal is to merge this tomorrow as `0.1.0` so that pacakge.json …
> Hide internal events from end user and standardize external events

- API.md
- src/edit_store.js
- src/store.js
Adds `draw.edit.start` and `draw.edit.end` events that fire when a feature is selected/deselected.
Closes #139 
cc @mcwhittemore
> Add edit selection events

- src/api.js
Currently they won't render because they are set to ready = false.
> set feature ready for rendering on add

- package.json
- src/store.js
This stops code like
```
map.on('draw.delete', function(geojson) { Draw.deselect(geojson.id); });
```
from emitting the `draw.set` event.
> `draw.delete` should be emitted after the feature is removed from the store

- package.json
Maybe a little overkill at this point but don't want to leave behind `0.13` yet
> Update mapbox-gl peerDependency

- API.md
- circle.yml
- package.json
- src/api.js
- src/control.js
- src/feature_types/polygon.js
- src/feature_types/square.js
- src/util.js
- test/api.test.js
- test/controls.test.js
- test/draw.test.js
- test/events.test.js
- test/geometry.test.js
- test/line.test.js
- test/mock-browser.js
- test/point.test.js
- test/polygon.test.js
- test/square.test.js
- test/store.test.js
- test/utils.js
Closes #235
Closes #200
Closes #197
This also makes it so `permanent` features aren't selectable with `Draw.select()`.
> Moving to a mock for tests

- src/draw_events.js
Hi guys,
I've found a serious issue while was working with this plugin. Let me try to explain what I mean. 
So, I place a shape on a map and make it `interactive: true` to always have it in editable state. And when I try to move shape on a map (the cycle is: mouse down on the shape -> move mouse -> mouse up) sometimes it works ok, but sometimes I drag the map itself instead of dragging the shape. 
I started investigate and that's what I found: when we receive `mouseDrag` event - we check if there is `activeDrawId` here: https://github.com/mapbox/mapbox-gl-draw/blob/dca6a21050f01995c61c80d3eaacaabc4eebc863/src%2Fdraw_events.js#L125. And if there is - we stop propagating event to move the shape (and not move the map). But the issue is that we set this  `activeDrawId` in handler for …
> Fix for issue when you drag a shape and instead of a shape map is dragged

- API.md
- src/options.js
- src/setup.js
- test/options.test.js
@kiRach we were using this in the 0.4 version of Draw, but when we made the major change @mayagao also restyled Draw and so we stopped using our own internal custom style. So I was wrong to think this was working for us... :( sorry.
This reenables custom styling and provides a test to help us not regress again. Can you confirm?
Closes #288
> fix custom styling

- bench/lib/mouse_draw.js
- bench/lib/mouse_trace.js
- src/events.js
- src/lib/euclidean_distance.js
- src/lib/mode_handler.js
- src/modes/direct_select.js
- src/modes/simple_select.js
- test/line.test.js
- test/point.test.js
- test/polygon.test.js
- test/utils.js
Treats clicks as mousedown + mouseup events that do happen without the mouse moving too far or too much time happening between them.
Fixes
The logic is borrowed from [iD](https://github.com/openstreetmap/iD/blob/d130c517b0a98c470aef269176bda729532f8ff1/js/id/behavior/draw.js#L34-L56).
@samanpwbb for the review.
> Synthetic clicks

- API.md
- src/modes/direct_select.js
- test/events.test.js
Throw error when using `direct_select` with points as mentioned in mapbox/mapbox-gl-draw#310
> Throw error when using direct_select with points

- API.md
- CHANGELOG.md
- debug/index.html
- package.json
- src/api.js
- src/events.js
- src/feature_types/feature.js
- src/feature_types/line_string.js
- src/feature_types/point.js
- src/feature_types/polygon.js
- src/lib/features_at.js
- src/lib/mode_handler.js
- src/lib/theme.js
- src/modes/simple_select.js
- src/render.js
- src/store.js
Updated render to only loop over the features that have changed and dropped zoom based rendering so that Draw doesn't need to loop over every feature on zoom.
When a feature is hot and updated the rendering performance is constant. When it goes cold Draw's rendering is constant but gl-js is not. We might want to look into having multiple cold sources based on the number of features in Draw...
With the earcut version of gl-js this is running at about 55fps on my computer with 20mb worth of data loaded. On the non-earcut version it runs around 33fps.
> Speed improvements

- .babelrc
- .gitignore
- package.json
Now if you `npm run coverage`, it runs the tests, then open a browser showing nyc's nice report.
> Add coverage script using nyc; closes #375

- API.md
- src/api.js
- src/lib/mode_handler.js
- src/lib/to_dense_array.js
- src/modes/direct_select.js
- src/modes/draw_line_string.js
- src/modes/draw_point.js
- src/modes/draw_polygon.js
- src/modes/simple_select.js
- src/render.js
- src/store.js
- test/store.test.js
- test/test_utils.js
This first commit adds `draw.select` and `draw.deselect` events so addresses #365. They are unit tested using Sinon spies on the `map.fire` function. Also fixed some things in Store based on the tests that I wrote.
Do we want to to eliminate the `draw.mode.simple_select.selected.start` events, replacing with these new events? Or keep the mode-specific events also?
I could use this PR to remove those and follow through with an event cleanup re: #367.
> New events

- API.md
- dist/mapbox-gl-draw.css
- src/api.js
- src/constants.js
- src/events.js
- src/lib/common_selectors.js
- src/lib/double_click_zoom.js
- src/lib/get_features_and_set_cursor.js
- src/lib/mode_handler.js
- src/lib/string_sets_are_equal.js
- src/modes/direct_select.js
- src/modes/draw_line_string.js
- src/modes/draw_point.js
- src/modes/draw_polygon.js
- src/modes/simple_select.js
- src/render.js
- src/store.js
- test/common_selectors.test.js
- test/draw_line_string.test.js
- test/interaction_events.test.js
- test/simple_select.test.js
- test/utils/after_next_render.js
- Add `Draw.getMode()` API function, so Studio could tell if it needed to update Draw's mode.
- Make `Draw.set()` re-render when it's done deleting.
- Prevent box selecting from happening because you shift+double-clicked to zoom out
- Exit `direct_select` mode if the selected feature has been deleted
- Add `Draw.setSelected()` to API as a preferable way to select items programmatically, instead of needing to change mode to `simple_select` and specifying features.
- Fix cursors so the right ones show and they change as the mouse moves.
- Fix this: create a feature, then before deselecting it try to drag it — it's like the browser tries to treat it as a file that you're dragging and dropping. Fixed by re-rendering the feature when you mousedown on it.
Might accumulate more ...
> Studio inspired fixes

- src/api.js
- src/modes/direct_select.js
- src/render.js
- src/setup.js
- test/api.test.js
@mcwhittemore:
Almost all of the changes in `api.js` are just indent changing, because I created the `api` object before the methods so it was easy to return without worrying about `this` context.
I have one test set failing because of `map.queryRenderedFeatures()` ...
> Cleanup and extend API tests

- src/api.js
- test/api.test.js
I found this bug while working in Studio. We need to make sure that if the selection is changed via `Draw.changeMode()`, there is a re-rendering.
> Render after changing selection

- src/modes/draw_line_string.js
- src/modes/draw_point.js
- src/modes/draw_polygon.js
- src/render.js
- test/draw_line_string.test.js
- test/draw_point.test.js
- test/draw_polygon.test.js
Ref #442.
This was a good bug to uncover, because it helped me understand the rendering better.
I realized that the `draw_*` mode's render function is being used to render *every feature on the map*, not just the feature that's being drawn. So the logic in there that might *not* render some `geojson` should *only apply to the active feature, the one being drawn*.
I refactored the mode render functions to clarify this and return early for inactive features, and improved the tests to address the situation and prevent a regression of bugs like #442 (where the render function ended up not rendering an inactive feature).
Since I was looking closely at the `render` function to debug this, I also found a way to simplify that and included it in the PR.
> Refactor render functions, improve tests; fixes #442

- package.json
- src/api.js
- src/render.js
- src/store.js
- test/store.test.js
`Draw.set()` invokes render twice. Once for `Draw.add()` and once for `Draw.delete()`. Since we use `throttle` to limit the number of times we processes all of the renders this means that part of the job is sent to gl-js, then 16ms happens, and than another part of the job is sent. This can lead to some weird rendering results (due to gl-js not ensuring setData calls are rendered in the right order?). This PR solves this problem by batching the two renders into one.
This could also be solved by moving from throttle to debounce, but debounced rendering feels laggy.
Replaces #441
@davidtheclark for the review
> Batch render calls invoked by Draw.set

- API.md
- src/api.js
- src/constants.js
- src/events.js
- src/ui.js
- test/api.test.js
Ref #267.
In the process of doing this I thought it would be a good idea to change `DRAW_LINE` to `DRAW_LINE_STRING`, for consistency with geojson types.
> Expose Draw.modes; closes #267

- src/events.js
- src/lib/move_feature.js
- src/modes/direct_select.js
- src/modes/simple_select.js
- test/direct_select.test.js
- test/interaction_events.test.js
- test/simple_select.test.js
- test/static.test.js
- test/utils/make_mouse_event.js
Re-take on PR #444 to close bug #419.
This time I used `events.js` to add the DOM listener, and added some appropriate tests.
@mcwhittemore, ready for review.
> Add mouseout and use it to cancel box select; fixes #419

- src/lib/throttle.js
- src/render.js
We ran into a bug in which the `draw.delete` event was firing twice before the next line of code, which clears the array of features to emit, was cleared. So we ended up with listeners thinking the same feature was deleted twice.
My guess as to why this was happening is because the firing of the event sent us down a completely synchronous code path that ended up looping us back to that very spot where the event fired. Then the event fired again before we got to that next line that clears the array. Solution, then, is to clear the array before firing the event.
cc @mcwhittemore
> Prevent deleted features emitting twice

- API.md
- src/events.js
- src/lib/mode_handler.js
- src/modes/direct_select.js
- src/modes/simple_select.js
- test/direct_select.test.js
- test/mode_handler.test.js
- test/simple_select.test.js
- test/utils/make_mouse_event.js
This PR introduces `mouseout` events and causes a `draw.update` event to fire if you've been dragging a feature or vertex and your mouse leaves the container.
Before this, we had a problem that you could drag-move something until your mouse leaves the container, release the mouse button outside, then return, and the feature would have changed its position but no` draw.update` event would have been fired. With these changes, a `draw.update` will be fired anytime you leave. (If you continue to hold the mouse button down and move back in, continuing the drag, then mouseup, ending the drag, you'll get another `draw.update` event.)
> Fire draw.update on mouseout when dragging

- src/api.js
The latest version of geojsonhint uses `level: "message"` instead of `level: "warn"` — so I just switched this to a positive check for `level: "error"`.
@mcwhittemore for review. If you think this is good, let's release so we can take advantage downstream.
> Fix geojsonhint error filter

- src/lib/features_at.js
- test/direct_select.test.js
- test/features_at.test.js
Fixes #509.
The problem was that `queryRenderedFeatures` was returning multiple versions of the same feature, as it can do, and we were not filtering out those duplicates. With this change I can no longer reproduce the bug.
> featuresAt returns unique features only

- API.md
`line` is not a valid option -- it seems that the doc is actually referring to `line_string`
> 'line_string' Option Correction in API Docs

- package.json
Needed the `t` to fix the UMD export
> Fixed typo in build command

- API.md
- CHANGELOG.md
- README.md
- debug/index.html
- index.js
- package.json
- server.js
- src/api.js
- src/modes/direct_select.js
- test/api.test.js
- test/direct_select.test.js
- test/draw_line_string.test.js
- test/draw_point.test.js
- test/draw_polygon.test.js
- test/interaction_events.test.js
- test/line_string.test.js
- test/options.test.js
- test/point.test.js
- test/polygon.test.js
- test/simple_select.test.js
- test/static.test.js
This PR renames draw for the last time!
In the other Mapbox maintained `mapbox-gl-js` controls we have settled on the `new MapboxNoun()` convention. This PR brings `MapboxDraw` into accord.
**Breaking Changes**
- The name has changed for `script tag` users.
- `MapboxDraw` now requires `new`.
> Rename `mapboxglDraw` to `MapboxDraw`

- README.md
- package.json
The peerDependencies do not include the latest Mapbox GL JS version, which causes an annoying nag when using npm.
> Update mapbox-gl peerDependencies to 0.29.0

- server.js
With the latest version of gl-js, we need to change the way the JS is served on the debug server.
> Fix debug server for latest gl-js

- API.md
The example had the id inside the geometry object.
> fix add() with specified feature id example

- package.json
Updates the `mapbox-gl` peer dependency to work with the latest version of GLJS. 
Also, greenkeeper appears to have updated all dependencies.
cc @mcwhittemore
> update peer dependencies for mapbox-gl

- package.json
Version bump for last [merge](https://github.com/mapbox/mapbox-gl-draw/pull/619) with new dependencies and peer dependencies.
> version 0.17.1 bump

- src/modes/direct_select.js
- src/store.js
The goal of this PR is to close #632 
In `direct_select` mode, entering the mode or clicking on a vertex saves the parent feature ID, the coordinate index, and the geometry of the selected vertex.
When a user drags the point, the point remains selected, but it's geometry value saved to the store remains the same. So calling `draw.getSelectedPoints` inside of a `draw.update` event handler will frequently return stale geometry.
To fix this, I make the `store._getSelectedCoordinates` method retrieve the coordinate geometry based on the store's (up-to-date) features, rather than the cached value in `store._selectedCoordinates`.
I also stop including coordinates in the `_selectedCoordinates` array at all, so that `direct_select` now only saves the parent feature ID and coordinate index of the …
> Don't cache selected points separately from other store features

- debug/index.html
- package.json
- src/constants.js
- src/lib/double_click_zoom.js
- src/setup.js
- src/store.js
- test/draw_line_string.test.js
- test/draw_polygon.test.js
- test/static.test.js
- test/store.test.js
- test/utils/create_map.js
- yarn.lock
Hey, this is a first draft of a change, which is intended to enable storage and consistent setting of map interaction settings when enabling Draw.
There's a couple of concepts in here:
1. The initial state is set and restored in `setup.js` using the Store
2. The initial state can be queried in the toggling of interactions so that settings are maintained
3. For now, it's been implemented in the `double_click_zoom.js` file and tested in the debug map and works well.
This PR is really a first pass, where I'm hoping to get feedback on the concept. After feedback I'll finish implementation for the other interactions.
I have an issue between the develop mode interactive site and the tests, in that the store and map are different, so either one or the other fails. This may be (probably is) my …
> Store initial map interaction settings

- .eslintrc
- test/store.test.js
Very small change to add an eslint rule to catch leftover `console.log`s. Also remove a `console.log` in a previous PR.
> Remove console log and add eslint rule to prevent repeat

- docs/MODES.md
This wasn't totally clear to me when I went about building a new draw mode. I realize that `defaultMode` and `modes` are documented in a different file, but it still tripped me up because it didn't quite click as to how I'd hook the mode in. Just  a suggestion, feel free to close or modify.
> Add example of adding draw mode to draw

- CHANGELOG.md
- src/events.js
Fixes #751.
Note, I'm still trying to build the 1.0.5 git working copy (npm install fails on gulp-sourcemaps, so I cant actually build the master branch at this moment...), so proper testing is limited at this stage. beyond what I also hand-patched in my build
> event.srcElement has limited support so fall back to event.target

- src/setup.js
Removing the draw control before the map is loaded throws errors related to missing layers.
This PR introduces a two part solution:
1. When the control is removed, stop waiting for map to load.
1. Check for source/layer presence before attempting to remove them.
fixes #572 
I would love feedback.
> Safely Remove Control

- src/render.js
- src/setup.js
As outlined in my support request, we are unable to make Mapbox Draw correctly render features added before the control has fully loaded, but there are no events or otherwise to properly indicate that the control is ready.
This PR forces the `ctx.store` to be dirty when doing the initial rendering following adding its layers.
The issue is that the `render` `cleanup()` function is being called even if the map isn't ready yet, and this function sets `store.isDirty=false`, meaning that any unrendered features are ignored.
I've also changed the order of operations for the `draw.render` event for a similar reason, so that changes made to the draw instance in response to this event aren't immediately forgotten.
> Race condition loading shapes

- .travis.yml
- README.md
- package.json
- src/setup.js
- src/store.js
- yarn.lock
Here's another way to do #771 that results in a much smaller PR
Ref #766
> Patch map.fire to format arguments passed to it.

- src/lib/string_set.js
- test/string_set.test.js
Closes #738
Closes #777
@mmoutenot do you take a look at this and confirm I've fixed the bug?
> allow features to have numeric ids

- debug/app.js
- debug/index.html
- server.js
Updating how the static page works a bit so that it can include the static mode.
This also updates it to use the latest version of the Geocoding plugin.
> Improve debug page

- src/modes/object_to_mode.js
Updates the mode to object code which converts an object following the mode interface into Draw's internal concept mode concept. The update makes sure that the selector for all events inherited from the interface is set to false so that the empty function code of the interface won't run.
This will reduce the amount of extra render calls as events that aren't directly implemented by a mode won't force renders anymore, but it does not solve #760 as any event handler implemented by a mode will still force a render even if that event handler does nothing to the source data.
This change means that the static custom mode will only force a render on setup.
@hyperknot if you can review that this solves your CPU problem in the static mode context that would be great.
> Don't run render on unused event handlers

- docs/MODES.md
Found this mode by @chriswhong to be very useful, so thought I'd link it in the repo. Can see it in action here: https://popfactfinder.planning.nyc.gov/
> Add link to radius mode

- docs/API.md
While this is mentioned in the bottom of the API.md in the styling section, it was not included as part of the section that lists all of the available options.
> Include userProperties in Options section of docs

- src/modes/index.js
Per #825, this fixes some redundant code in `modes/index.js`.
cc @jelmervdl
> clean up the most list index file

- test/direct_select.test.js
- test/simple_select.test.js
- test/static.test.js
Several Sinon tests were failing (`direct_select`, `simple_select`, and `static`) with the error [spyFunction].reset is not a function, as described in #838.
Changing the order of the spy setup call to after the calls to `map.addControl(Draw);` appears to fix the problem. It seems probable that the adding the control somehow overwrites the spy function, and so spying after addition avoids this situation. Failing tests run successfully after the swap.
> change ordering of spy creation to avoid overwrites

- package.json
@ansis it would be great if we still can get this into the 1.1.0 release. It seems like you haven't published on npm.
This fixes https://github.com/mapbox/mapbox-gl-draw/issues/827
> Upgrade mapbox-gl peer dependency to match dev dependencies

- docs/MODES.md
I've published an npm module called mapbox-gl-draw-circle, including the link for the same in list of available modes.
> Added CircleMode to MODES.md

- docs/MODES.md
we have created a new mode via npm called "@geostarters/mapbox-gl-draw-rectangle-assisted-mode".
Could you add the link to the list modes?
https://www.npmjs.com/package/@geostarters/mapbox-gl-draw-rectangle-assisted-mode
https://github.com/geostarters/mapbox-gl-draw-assisted-rectangle-mode
thanks
> Add Assisted Rectangle Mode reference to MODES.md

- src/ui.js
Relates to this issue https://github.com/mapbox/mapbox-gl-draw/issues/698. The buttons should actually toggle the mode you're in since it toggles `active` css class. If this makes sense I can modify the tests
> draw buttons should cancel on toggle

- docs/MODES.md
- coords should be an array of `{feature_id: 'string', coord_path: 'string'}` as per https://github.com/mapbox/mapbox-gl-draw/blob/5b2280817c901d93b05c937a7bdb2efb8afefe0c/src/modes/mode_interface_accessors.js#L33, not `{coord_path: 'string', feature_id: 'string'}`
> fix documentation for this.setSelectedCoordinates

- src/modes/direct_select.js
- test/direct_select.test.js
Fixes https://github.com/mapbox/mapbox-gl-draw/issues/897 by correctly sorting coordinate paths prior to deletion.
We're using "coordinate paths" to store which vertices are selected. These paths are stringified indices into the coordinates array, and can be multiple levels deep separated by `.`. When deleting vertices, we sort them in reverse order to make sure that we invalidate the indices by deleting vertices that come before another vertices scheduled for deletion. This works if we have fewer than 10 vertices. However, the alphabetical sort means that we'd delete note `10` before node `9`. This PR fixes this by using a numeric sort.
> Trash correct vertices by changing sort to be numeric-aware

- src/lib/mode_handler.js
- src/modes/direct_select.js
- src/modes/object_to_mode.js
- src/modes/simple_select.js
Reduces CPU usage and fixes https://github.com/mapbox/mapbox-gl-draw/issues/760
CPU usage is still high when moving the mouse, but the remaining CPU usage is in queryRendereredFeatures which is used to determine the shape of the mouse pointer.
> Skip rerenders for mousemove handlers when in selection modes

- README.md
Closes https://github.com/mapbox/mapbox-gl-draw/issues/997.
Also updates referenced CDNs from `v1.0.9` to `v1.2.0`.
> Update README.md with changes from v1.2.0 release

- docs/MODES.md
I have created geodesic modes plugin. Most of the modes simply inherit from the original MapboxDraw modes, and wrap `toDisplayFeatures` function with geodesic calculation.
```
const DrawLineString = MapboxDraw.modes[Constants.modes.DRAW_LINE_STRING];
const DrawLineStringGeodesic = { ...DrawLineString };
DrawLineStringGeodesic.toDisplayFeatures = function(state, geojson, display) {
const displayGeodesic = (geojson) => {
const geodesicGeojson = createGeodesicFeature(geojson, { ctx: this._ctx });
geodesicGeojson.forEach(display);
};
DrawLineString.toDisplayFeatures.call(this, state, geojson, displayGeodesic);
};
```
There is also a static mode which can be used to render geodesic map features without using the drawing capabilities. It is useful because geodesic calculations are isolated …
> Add link to geodesic modes

- package.json
I'm attempting to copy the development environment set up for this project in another mapbox-gl plugin (mapbox-gl-accessibility), and I noticed this script (`start-server`) doesn't seem to do anything.
> Remove unused start-server script

- README.md
The PR adding TS definition files just got merged to definitely typed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox__mapbox-gl-draw/index.d.ts
Thir PR updates the README.md file to better explain what typescript users should do to install the ts definition files.
related issues: https://github.com/mapbox/mapbox-gl-draw/issues/842
> Add typescript install instructions

- package.json
- src/api.js
- test/api.test.js
- yarn.lock
Closes #1051, closes #1020, closes #1049. Upgrades some dependencies to pass security audit, and removes GeoJSON validation which wasn't very useful for its added size, was applied inconsistently, and relied on an unmaintained library with highly vulnerable transitive deps. Removing it is technically not too breaking since the code that worked before will continue working after the upgrade.
> Remove GeoJSON validation

- docs/EXAMPLES.md
Error in the docs, the style for "gl-draw-polygon-stroke-active" was not closed properly
> Fix documentation example error

- dist/mapbox-gl-draw.css
There were several CSS classes no longer being applied because their parent `.mapbox-gl-draw_ctrl-draw` never exists.  Instead of `.mapbox-gl-draw_ctrl-draw > button` to style buttons in the controls, the css is changed to just use `.mapbox-gl-draw_ctrl-draw-btn`. 
This restores a different style for when a button is active (this PR sets the active background color to be the same gray used when hovering a mapbox control button.)
Closes #1124
> update css for control buttons

- src/lib/sort_features.js
As simple_select sometimes renders lines as `MultiLineString` geometry, `sortFeatures()` should handle this type or midpoint clicking would fail.
This could fix issue #1117.
> Adding sorting rank value for MultiLineString

- index.js
- src/lib/index.js
- Saw there was an issue for exposing API's to make it easier to write custom draw modes - https://github.com/mapbox/mapbox-gl-draw/issues/1056
- Experiencing a similar issue here - https://github.com/aws-amplify/maplibre-gl-draw-circle
- Added everything in `Constants` and `Lib` to the `MapboxDraw` default export
-  Considered making them separate named exports from the default but wanted to keep it in line with `modes` which is also added directly onto the `MapboxDraw` object
> chore: export constants and lib through MapboxDraw

- src/events.js
- test/utils/key_events.js
fix #1135
Had to update test events to include a contains() function.
> In key event handler, check for map canvas using classList.contains()

- src/setup.js
> Fix boxZoom bug

- src/lib/features_at.js
- test/features_at.test.js
- test/utils/create_map.js
Fixes #1183
Updated fetures_at.js's `featuresAt` function to verify a style layer exists before adding it to queryParam.layers for the map.queryRenderedFeatures function. The mapbox-gl-draw style layers are removed during a map.setStyle call and are not added back until the data event (with type of style) is received. If the featuresAt function includes missing styles, the map.queryRenderedFeatures function will fire an error (https://github.com/mapbox/mapbox-gl-js/blob/11ea4f82e2d04041ef33339ac51909e876eed910/src/style/style.js#L1111C1-L1112C1)
Updated test/utils/create_map.js mock of mapbox-gl-js's map to include a very basic style layer management.
Updated features_at.test.js to better mock the source/style handling of mapbox-gl-js so that a test case could be added to demonstrate this …
> Fix for layer not found error in featuresAt function

- src/api.js
> Trigger featureChanged on feature props change

- src/events.js
Touchstart and touchmove listeners added to the document by default as passive, so that calls to preventDefault will be ignored and will create a browser error like "Unable to preventDefault inside passive event".
The difference between this solution and the previous one tring to fix that bug (https://github.com/mapbox/mapbox-gl-draw/commit/5a904720cf7405ccecfbb3957dd8c63bf04b5829) is that we leave preventDefault inside the touchend event. 
More info on: https://chromestatus.com/feature/5093566007214080 and https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#compatibility_with_mouse_events
Fixes #1019
> Remove preventDefault() on touchstart and touchmove events

- CHANGELOG.md
- README.md
- package.json
* Fix for layer not found error in `featuresAt` function by @caldwellc in https://github.com/mapbox/mapbox-gl-draw/pull/1194
* Trigger `featureChanged` on feature props change by @wyozi in https://github.com/mapbox/mapbox-gl-draw/pull/1196
* Remove `preventDefault()` on `touchstart` and `touchmove` events by @Archetylator in https://github.com/mapbox/mapbox-gl-draw/pull/1195
> Release v1.4.3

- src/api.js
https://github.com/mapbox/mapbox-gl-draw/pull/1196 intended to add a call to `featureChanged` any time a feature was `add()`ed with modified properties, however it has a bug in that the check came after assignment.
An alternative to this fix would be to move the assignment inside the `if()` body, but that could break other code that depended on referential equality after calling `add()`.
I verified the fix by hacking the demo to include a button which modified a property on a feature, and also hacked the stylesheet to render that property as a label. Code here: https://github.com/petermoz/mapbox-gl-draw/commit/132d2d2da8aff3ab0246bd9e8036725bb097e1d4
I had a look at adding tests but couldn't figure out how to best get access to `store.getChangedIds` from the the API test. Happy to add …
> fix: trigger featureChanged on feature props change

- debug/app.js
- debug/index.html
- Updated mapbox-gl@2 to mapbox-gl@3 in sandbox for testing purpose
> [GLJS-612] Updated sandbox to GLJSv3

- rollup.config.js
- src/lib/theme.js
- src/setup.js
- test/fixtures/style_with_sources.json
- test/utils/create_map.js
* Keep dashed line for the active state in theme. Fix after https://github.com/mapbox/mapbox-gl-draw/pull/1078
* Drop `map.fire` monkey patch. We no longer need this patch since we support both `map.fire` interfaces in GL JS https://github.com/mapbox/mapbox-gl-js/pull/6604
> Small fixes

- package.json
https://github.com/mapbox/mapbox-gl-draw/pull/1242 switched project to Vite and ESM. This means that this project currently supports node version `^18.0.0 || >=20.0.0` https://vitejs.dev/guide/#scaffolding-your-first-vite-project
By adding `engines.node` to `package.json` we gain some extra features:
- Can automatically create a warning, when someone uses a wrong version
- Automatically use defined Node version, when running project via pnpm
- It will probably also be picked up by CI/CD
> chore: Update package.json to Node.js version 18.0.0 or higher

- docs/API.md
- src/api.js
- src/constants.js
- src/feature_types/feature.js
- src/modes/mode_interface_accessors.js
- src/options.js
- src/store.js
- test/api.test.js
- test/feature.test.js
- test/interaction_events.test.js
- test/options.test.js
- test/store.test.js
- Add `suppressAPIEvents` (`true` by default) option to `Draw` to emit events after API methods (like `add`, `delete`, etc) calls
> Emit events on API call with `suppressAPIEvents: false`

- package-lock.json
- package.json
- src/api.js
- src/feature_types/feature.js
- src/feature_types/multi_feature.js
- src/lib/id.js
- test/api.test.js
- test/utils/create_feature.js
As it was dicovered in #1274 `hat` module seems outdated and we need to migrate to another simple library for generating ID of features. Tried to keep compatible with old generator behaviour as much as possible
> Replace identifier library with nanoid

- package.json
At the moment, the release version of this package doesn't work anymore when imported into another project.
This fix allows ESM imports to work again.
> fix: update exports to work with current release workflow

- src/ui.js
- test/ui.test.js
Follow-up to #1209 
- Fixed ordering of buttons according to current keybindings (1 for point, 2 for line and 3 for polygon)
- Fixed tooltip keybinding hint
> Fix keybindings ordering and tooltips
